app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

from flask_login import UserMixin

from app.database import db
from app.login import login


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(32), index=True, unique=True)
    email = db.Column(db.String(64), unique=True)
    password_hash = db.Column(db.String(128))
    links = db.relationship('Link', backref='user')

    def __repr__(self):
        return f'<User {self.username}>'

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    full_link = db.Column(db.String)
    page = db.Column(db.String, unique=True)
    short_link = db.Column(db.String)
    visits = db.Column(db.Integer, default=0)
    created = db.Column(db.DateTime, index=True, default=datetime.now())

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f'<ID {self.id}>'

    def get_date(self):
        return self.created.strftime('%d.%m.%y %H:%M')

app/link/forms.py
from wtforms import Form, StringField
from wtforms.validators import DataRequired, URL


class LinkForm(Form):
    full_link = StringField(
        'Full link',
        [
            DataRequired(),
            URL(require_tld=False, message='URL не валидный.')
        ]
    )

app/user/forms.py
from wtforms import Form, StringField, PasswordField, BooleanField
from wtforms.validators import Email, DataRequired, EqualTo, Length, ValidationError

from app.models import User


class LoginForm(Form):
    email = StringField(
        'Email адрес',
        [
            DataRequired(),
            Email()
        ]
    )
    password = PasswordField(
        'Пароль',
        [
            DataRequired()
        ]
    )
    remember_me = BooleanField('Запомнить меня')


class SignupForm(Form):
    username = StringField(
        'Username',
        [
            DataRequired(),
            Length(min=5, message='Минимальное к-во символов 5, максимальное - 32.')
        ]
    )
    email = StringField(
        'Email адрес',
        [
            DataRequired(),
            Length(max=64, message='Максимальное к-во символов 64.'),
            Email()
        ]
    )
    password = PasswordField(
        'Пароль',
        [
            DataRequired(),
            Length(min=8, max=32, message='Минимальное к-во символов 8, максимальное - 32.')
        ]
    )
    password2 = StringField(
        'Повторите пароль',
        [
            DataRequired(),
            EqualTo('password', message='Пароли не совпадают.')
        ]
    )

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Пожалуйста, используйте другой username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Пожалуйста, используйте другой email.')

app/__init__.py
from flask import Flask

from config import Config
from .database import db
from .login import login


def create_app(config_filename=Config):
    app = Flask(__name__)
    app.config.from_object(config_filename)

    db.init_app(app)
    with app.test_request_context():
        db.create_all()

    login.init_app(app)

    import app.user.controllers as user
    import app.link.controllers as link

    app.register_blueprint(user.module)
    app.register_blueprint(link.module)

    return app

app/link/controllers.py
import string
from random import choice

from flask import Blueprint, render_template, request, redirect, current_app, jsonify
from flask_login import current_user, login_required

from app.models import db, Link
from .forms import LinkForm


module = Blueprint('link', __name__)


def log_error(*args, **kwargs):
    current_app.logger.error(*args, **kwargs)


def make_page():
    alphabet = string.ascii_letters + string.digits
    page = ''.join(choice(alphabet) for i in range(8))
    return page


@module.route('/', methods=['GET'])
def index():
    form = LinkForm()
    return render_template('index.html', form=form)


@module.route('/process', methods=['POST'])
def process():
    form = LinkForm(request.form)
    if form.validate():
        page = make_page()
        short_link = request.host_url + page
        link = Link(page=page, short_link=short_link, **form.data)
        if current_user.is_authenticated:
            link.user = current_user
        db.session.add(link)
        db.session.commit()
        return jsonify({'short_link': short_link})
    return jsonify({'errors': form.full_link.errors[-1]})


@module.route('/<page>')
def redirect_link(page):
    link = Link.query.filter_by(page=page).first()
    link.visits += 1
    db.session.commit()
    return redirect(f'{link.full_link}')


@module.route('/links', methods=['GET'])
@login_required
def link_list():
    links = Link.query.filter_by(user=current_user).order_by(Link.created.desc())
    return render_template('links.html', links=links)

app/user/controllers.py
from flask import Blueprint, redirect, url_for, flash, render_template, request
from flask_login import current_user, login_user, logout_user

from app.models import db, User
from .forms import LoginForm, SignupForm


module = Blueprint('user', __name__)


@module.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('link.index'))
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Не валидный email или пароль.')
            return redirect(url_for('user.login'))
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('link.index'))
    return render_template('login.html', form=form)


@module.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('link.index'))


@module.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('link.index'))
    form = SignupForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('link.index'))
    return render_template('signup.html', form=form)

app/templates/base.html
<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>SHORT URL</title>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <a class="navbar-brand" href="{{ url_for('link.index') }}">SHORT URL</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('link.link_list') }}">Список ссылок</a>
            </li>
            {% endif %}
        </ul>
    </div>
    {% if current_user.is_authenticated %}
    <span class="navbar-text mr-sm-2">Приветствуем, {{ current_user.username }}</span>
    <a class="btn btn-outline-info my-2 my-sm-0" href="{{ url_for('user.logout') }}" role="button">Выход</a>
    {% else %}
    <span class="navbar-nav mr-sm-2">
            <a class="nav-link" href="{{ url_for('user.signup') }}">Регистрация</a>
    </span>
    <a class="btn btn-outline-info my-2 my-sm-0" href="{{ url_for('user.login') }}" role="button">Вход</a>
    {% endif %}
</nav>

<div class="container">
    <div class="text-center">
        <h1 class="h3 mb-3 font-weight-normal">
            {% block header %}
            {% endblock header %}
        </h1>
    </div>

    {% block content %}{% endblock content %}

</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script type=text/javascript src="{{ url_for('static', filename='js/form.js') }}"></script>

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}


{% block header %}Сокращение ссылок{% endblock header %}

{% block content %}

<div class="text-center">
    <p class="col-md-6 offset-md-3">Вставьте ссылку в поле, нажмите кнопку <code>Отправить</code> и получите
        сокращенную ссылку.
    {% if current_user.is_anonymous %}
        Чтобы сохранять все ссылки, <a href="{{ url_for('user.login') }}">Войдите</a> или <a
                href="{{ url_for('user.signup') }}">Зарегистрируйтесь</a>.
    {% endif %}
    </p>
</div>
<div class="col-md-6 offset-md-3">
    <form>
        <div class="form-group">
            {{ form.full_link(class="form-control", placeholder="URL", type="text", id="full_linkInput") }}
            <input class="form-control" id="errorInput" type="text" style="display:none;" readonly>

            <div class="input-group mb-3" style="display:none;" id="successDiv">
                <input class="form-control" id="successInput" type="text" readonly aria-describedby="button-addon2">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="button-addon2" onclick="myFunction()">
                        Copy
                    </button>
                </div>
            </div>

        </div>
        <button class="btn btn-info btn-lg btn-block" type="submit" id="full_linkButton">Отправить</button>
        <a class="btn btn-secondary btn-lg btn-block" href="{{ url_for('link.index') }}" role="button"
           style="display:none;" id="successButton">Обновить</a>
    </form>
</div>


<!-- Script JavaScript -->
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>

<script>
    $(document).ready(function () {

        $('form').on('submit', function (event) {

            event.preventDefault();

            $.ajax({
                data: {
                    full_link: $('#full_linkInput').val()
                },
                type: 'POST',
                url: '/process',
                dataType: 'json'
            })
                .done(function (data) {
                    if (data.short_link) {
                        $('#full_linkInput').css('display', 'none');
                        $('#successDiv').show();
                        $('#successInput').val(data.short_link);
                        $('#full_linkButton').css('display', 'none');
                        $('#successButton').show();
                    } else {
                        $('#full_linkInput').css('display', 'none');
                        $('#errorInput').val(data.errors).show();
                        $('#full_linkButton').css('display', 'none');
                        $('#successButton').show();
                    }

                })

        });

    });
</script>

<script>
    function myFunction() {
        var copyText = document.getElementById("successInput");
        copyText.select();
        document.execCommand("copy");
    }
</script>

{% endblock content %}

app/templates/links.html
{% extends 'base.html' %}


{% block header %}Список ссылок{% endblock header %}


{% block content %}

<div class="col-md-6 offset-md-3">

    <ul class="list-group">
        {% for link in links %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ link.short_link }}
            <span class="badge badge-info badge-pill">{{ link.visits }}</span>
        </li>
        {% endfor %}
    </ul>

</div>

{% endblock content %}

app/templates/login.html
{% extends 'base.html' %}


{% block header %}Вход в систему{% endblock header %}

{% block content %}

<div class="col-md-4 offset-md-4">

    {%- with messages = get_flashed_messages(with_categories=true) -%}
    {% if messages %}
    <div class="flashes">
        {% for category, message in messages %}
        <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {%- endwith %}

    <form action="{{ url_for('user.login') }}" method="post">
        <div class="form-group">
            {{ form.email.label }}
            {{ form.email(class="form-control", placeholder="Введите email", type="email", size=64) }}
        </div>
        <div class="form-group">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder="Введите password", type="password", size=32) }}
        </div>
        <div class="form-group form-check">
            {{ form.remember_me(type="checkbox", class="form-check-input") }}
            {{ form.remember_me.label }}
        </div>
        <button type="submit" class="btn btn-info btn-block">Войти</button>
    </form>

</div>

{% endblock content %}

app/templates/signup.html
{% extends 'base.html' %}


{% block header %}Регистрация{% endblock header %}

{% block content %}

<div class="col-md-4 offset-md-4">

    <form action="{{ url_for('user.signup') }}" method="post">
        <div class="form-group">
            {{ form.username.label }}
            {{ form.username(class="form-control", placeholder="Введите username", size=32) }}
            {% for error in form.username.errors %}
            <small class="form-text text-muted">{{ error }}</small>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.email.label }}
            {{ form.email(class="form-control", placeholder="Введите email", type="email", size=64) }}
            {% for error in form.email.errors %}
            <small class="form-text text-muted">{{ error }}</small>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder="Введите пароль", type="password", size=32) }}
            {% for error in form.password.errors %}
            <small class="form-text text-muted">{{ error }}</small>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.password2.label }}
            {{ form.password2(class="form-control", placeholder="Повторите пароль", type="password", size=32) }}
            {% for error in form.password2.errors %}
            <small class="form-text text-muted">{{ error }}</small>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-info btn-block">Зарегистрироваться</button>
    </form>

</div>

{% endblock content %}